import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const clashDisplayFont = localFont({
  src: "../fonts/ClashDisplay-Bold.otf",
});
const clashDisplayvar = localFont({
  src: "../fonts/ClashDisplay-Medium.otf",
});
const clashDisplaylight = localFont({
  src: "../fonts/ClashDisplay-Light.otf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${clashDisplayFont.className} ${clashDisplaylight.className} ${clashDisplayvar.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
